### ISSUE TITLE
CMake - avoid option collisions

### ISSUE THREAD

**Issue by SGSSGene** [NUCLEAR-BOMB/option#1]
I see you have options like `BUILD_TEST`. You might want to Prefix them like `OPTION_BUILD_TEST` to make clear that these are options of your projects. This helps a lot, avoiding collisions with names that other libraries are using.

**Comment by NUCLEAR-BOMB** [comment]
@SGSSGene Thanks for suggestion. Implemented in bdc0695. This change is included in [v1.1.0](https://github.com/NUCLEAR-BOMB/option/releases/tag/v1.1.0) release.
